### ISSUE TITLE
Inicio

### ISSUE THREAD

**Issue by pablocolorim** [ColorimMx/UnitechInventario#2]
- [x] Lógica Developer Conteo.
- [x] Lógica Developer Ubicación.
- [x] DB Tipo de EAN.
- [x] Lógica Developer Código EAN.
- [x] Ejecutable Inicio.

**Comment by MiguelColorim** [comment]
Se envio correo a Yuri para que nos envie las descripciones y cantidades de los corrugados, se trabajara con una base de ejemplo y cantidades obtenidas en el inventario previo

**Comment by MiguelColorim** [comment]
Se integra base de datos, conforme a lo que indiquen en al DB se realizara la mulplicacion para obtener las piezas por caja en presentacion de corrugado, colectiva y empaque.

**Comment by MiguelColorim** [comment]
Se detecta limite de software para la creacion del modulo de Inicio, se comentara este motivo para el cambio a modulos individuales para los conteos 1,2 y 3.
